# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workoutlog",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(fields=["user", "-date"], name="logs_wl_user_date_idx"),
        ),
    ]
